name: Go Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.23.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go install

      - name: Test
        run: |
          go test -v -cover ./... -coverprofile=coverage.out -coverpkg=./...
          go tool cover -func=coverage.out -o coverage.out

      - name: Generate Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1
        if: ${{ runner.os == 'Linux' }}  # Only run this on Linux
        with:
          green: 80
          filename: coverage.out

      - name: Auto Commit Coverage Badge to README
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit
        with:
          commit_message: "Apply Code Coverage Badge"
          skip_fetch: true
          skip_checkout: true
          file_pattern: ./README.md

      - name: Push Changes
        if: steps.auto-commit.outputs.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload Coverage Reports to Codecov
        if: ${{ runner.os == 'Linux' }}
        uses: codecov/codecov-action@v3
